zabbix_db_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;netology-diploma
          33643734353463666162653263656632376366316463383935623437303164653461363838363139
          6261323030613639306330663733373438393337643030610a393866396337613836626336653964
          63393563633361326236396566373633353431633031643431623736366364653266363532653934
          3662316433633936370a383363373838336636343531343332393031333939623732353835666536
          6564