---
- name: Деплой Nginx и сайта
  hosts: webservers
  become: yes

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy index.html
      copy:
        src: ~/netology-diploma/ansible/files/index.html
        dest: /var/www/html/index.html
        mode: '0644'
      notify: Restart Nginx

    - name: Copy styles.css
      copy:
        src: ~/netology-diploma/ansible/files/styles.css
        dest: /var/www/html/styles.css
        mode: '0644'
      notify: Restart Nginx

    - name: Ensure Nginx started
      service:
        name: nginx
        state: started
        enabled: yes